### ISSUE TITLE
[PERF] Admin Order grid performance issues

### ISSUE THREAD

**Issue by lbajsarowicz** [ParadoxLabs-Inc/tokenbase#1]
# :turtle: Performance Issue

## Current behavior
Your Tokenbase extension (4.5.4) version, in a `\ParadoxLabs\TokenBase\Plugin\OrderCollectionPaymentLoadTokenbaseId::beforeAddItem` method performs a call to `getPayment` on all the Sales collections in the global scope (not limited to Adminhtml only):
```

    <type name="Magento\Sales\Model\ResourceModel\Order\Collection">
        <plugin name="orderCollectionPaymentLoadTokenbaseId" type="ParadoxLabs\TokenBase\Plugin\OrderCollectionPaymentLoadTokenbaseId" />
    </type>
```
That causes a significant performance overhead reported by Blackfire (see attachment).

## Expected behavior
Our recommendation for you is to:
1. Limit attaching plugin only to the areas affected (move entry to `adminhtml/di.xml`)
2. If you really need to use Payment, please prefetch payments for the whole collection, instead calling n+1
3. Reconsider if you really need to affect whole `Magento\Sales\Model\ResourceModel\Order\Collection` or it's enough to `Magento\Sales\Model\ResourceModel\Order\Grid\Collection`

## What is the motivation / use case for changing the behavior?
Performance issues

## Environment

<pre><code>
TokenBase version: 2.5.4
Magento version: 2.4.6-p1
PHP version: 8.1

Others:

</code></pre>

**Comment by rhoerr** [comment]
Thank you Lukasz. I'll review your proposed changes this week.
